### ISSUE TITLE
User Profile Driver Error

### ISSUE THREAD

**Issue by surtic86** [JcPires/Project-Cars-DS-LiveApp#20]
I found a Bug on the User Profile. 

Why should there be more then one Driver per User? Where do i link the User to the Driver?

```
Cannot read property 'length' of undefined
  at eval (<anonymous>:29:1658)
  at eval (<anonymous>:29:3696)
  at /gameservers/pcars/live_app/node_modules/ejs/lib/ejs.js:250:15
  at Object.exports.render (/gameservers/pcars/live_app/node_modules/ejs/lib/ejs.js:288:13)
  at Object.exports.renderFile (/gameservers/pcars/live_app/node_modules/ejs/lib/ejs.js:318:20)
  at [object Object].module.exports [as engine] (/gameservers/pcars/live_app/node_modules/sails/node_modules/ejs-locals/index.js:85:7)
  at [object Object].View.render (/gameservers/pcars/live_app/node_modules/sails/node_modules/express/lib/view.js:76:8)
  at Function.app.render (/gameservers/pcars/live_app/node_modules/sails/node_modules/express/lib/application.js:523:10)
  at ServerResponse.res.render (/gameservers/pcars/live_app/node_modules/sails/node_modules/express/lib/response.js:827:7)
  at ServerResponse._addResViewMethod.res.view (/gameservers/pcars/live_app/node_modules/sails/lib/hooks/views/res.view.js:237:16)
  at /gameservers/pcars/live_app/api/controllers/UserController.js:60:11
  at wrapper (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at _normalizeCallback.callback.success (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
  at returnResults (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:180:9)
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:86:16
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
  at Object.async.forEachOf.async.eachOf (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:227:20)
  at Object.async.forEach.async.each (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:433:11
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:572:5
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
  at Object.async.forEachOf.async.eachOf (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:227:20)
  at Object.async.forEach.async.each (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
  at [object Object]._buildChildOpts (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:461:9)
  at [object Object]._execChildOpts (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:429:8)
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:80:10
  at wrapper (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at _normalizeCallback.callback.success (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
  at /gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:167:7
  at wrapper (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
  at applyInOriginalCtx (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
  at wrappedCallback (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
  at _normalizeCallback.callback.success (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
  at _switch (/gameservers/pcars/live_app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
  at /gameservers/pcars/live_app/node_modules/sails-mysql/lib/connections/spawn.js:114:16
  at Object.module.exports.poolfully [as releaseConnection] (/gameservers/pcars/live_app/node_modules/sails-mysql/lib/connections/release.js:28:12)
  at /gameservers/pcars/live_app/node_modules/sails-mysql/lib/connections/spawn.js:99:35
  at Query._callback (/gameservers/pcars/live_app/node_modules/sails-mysql/lib/adapter.js:838:11)
  at Query.Sequence.end (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
  at Query._handleFinalResultPacket (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
  at Query.EofPacket (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
  at Protocol._parsePacket (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
  at Parser.write (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
  at Protocol.write (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
  at Socket.<anonymous> (/gameservers/pcars/live_app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:92:28)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
 { [TypeError: /gameservers/pcars/live_app/views/User/profile.ejs:25
    23|                     <div class="col-sm-4">
    24|                       <input type="text" class="form-control" id="steam_id" value="
 >> 25|                       <% if(user.driver.length > 0){ %><%= user.driver[0].steam_id %><% } %>
    26|                       ">
    27|                     </div>
    28|                     <div class="col-sm-2"><input type="submit" value="<%= __('update') %>" class="btn btn-primary" /></div>

Cannot read property 'length' of undefined] path: '/gameservers/pcars/live_app/views/User/profile.ejs' }
```

**Comment by surtic86** [comment]
Okey i think it should be 

```
if(user.driver !== undefined)
```

and not 
```
if(user.driver.length > 0)
```
