### ISSUE TITLE
Listener crash with dedicated sever protocol 1.0.1.27

### ISSUE THREAD

**Issue by thmxv** [JcPires/Project-Cars-DS-LiveApp#28]
Somebody has a fix there:
https://github.com/arnekaulfuss/Project-Cars-DS-LiveApp/tree/patch-3.0

I tested and it works, you might want to review it.

**Comment by vbabiy** [comment]
```
error: Sending 500 ("Server Error") response:
 ReferenceError: user is not defined
  at module.exports (/home/steam/Project-Cars-DS-LiveApp/api/policies/isAuthenticated.js:22:14)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at nextRoute (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:187:7
  at clearHeaders (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/cors/index.js:209:3)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at nextRoute (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:187:7
  at sails.router.bind._middlewareType (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/csrf/index.js:102:11)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at nextRoute (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:187:7
  at _addResViewMethod (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/views/res.view.js:325:3)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at nextRoute (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:187:7
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/i18n/index.js:35:7
  at Object.i18nInit [as init] (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/i18n/i18n.js:89:5)
  at addLocalizationMethod (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/i18n/index.js:33:11)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at nextRoute (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:187:7
  at addResponseMethods (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/responses/index.js:178:11)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at nextRoute (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:187:7
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/request/index.js:107:13
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/connect-flash/lib/flash.js:21:5
  at addMixins (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/request/index.js:86:11)
  at routeTargetFnWrapper (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/router/bind.js:179:5)
  at callbacks (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
  at param (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/lib/router/index.js:33:10)
  at next (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.xPoweredBy [as handle] (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/http/middleware/defaults.js:193:7)
  at next (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.methodOverride [as handle] (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/method-override/index.js:65:14)
  at next (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at next (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:171:9)
  at Object._parseHTTPBody [as handle] (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/skipper/index.js:62:14)
  at next (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/lib/hooks/http/middleware/defaults.js:52:22
  at Object.<anonymous> (/home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/express/node_modules/connect/node_modules/express-session/index.js:345:9)
  at Object.immediate._onImmediate (timers.js:381:16)
  at processImmediate [as _immediateCallback] (timers.js:363:15)
 [ReferenceError: user is not defined]
Server start!

TypeError: Cannot read property 'list' of undefined
  at /home/steam/Project-Cars-DS-LiveApp/api/hooks/pcarsServer/index.js:607:47
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:629:17
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:154:25
  at /home/steam/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:626:21
  at /home/steam/Project-Cars-DS-LiveApp/api/hooks/pcarsServer/index.js:594:15
  at Object.helpers.parseBody (/home/steam/Project-Cars-DS-LiveApp/node_modules/request-json/main.js:74:12)
  at Request._callback (/home/steam/Project-Cars-DS-LiveApp/node_modules/request-json/main.js:119:24)
  at Request.self.callback (/home/steam/Project-Cars-DS-LiveApp/node_modules/request-json/node_modules/request/request.js:344:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/home/steam/Project-Cars-DS-LiveApp/node_modules/request-json/node_modules/request/request.js:1239:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/home/steam/Project-Cars-DS-LiveApp/node_modules/request-json/node_modules/request/request.js:1187:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:492:13)
```

**Comment by vbabiy** [comment]
Getting that when I start the listener

**Comment by thmxv** [comment]
Apparently this project is dormant.
Sutic86's fork is the new place of development for this app:
https://github.com/surtic86/Project-Cars-DS-LiveApp
